### ISSUE TITLE
Should these email addresses, phone numbers, and URLs be public?

### ISSUE THREAD

**Issue by kennethgillen** [karel-brinda/ligm-business-cards#1]
Hi,

Just wondering if all of these contact details should in fact be public? Do these people consent to such linked contact details all being in plaintext in the public domain?

Best regards,

Kenny

**Comment by karel-brinda** [comment]
Hi Kenny,

thank you for your ticket.

All these people actively participated in uploading their business contacts to this repository. We had a special session during which we did it. However, I completely agree that there is no reason to keep there their business cards as most of them already graduated.

Best

Karel
